import { Meteor } from 'meteor/meteor';
import { WebApp } from 'meteor/webapp';
const fs = require('fs');

const Url = require('url');

WebApp.connectHandlers.use("/.well-known/acme-challenge/", function(req, res, next) {
  const challengesDir = Meteor.settings.letsEncryptChallengesDir || Meteor.settings.private.letsEncryptChallengesDir;
  let challengeFilename = Url.parse(req.url).pathname;

  // strip out characters that aren't usually in tokens generated by the Let's Encrypt certbot
  challengeFilename = challengeFilename.replace(/[^a-zA-Z0-9\-_\.]+/g, '');

  let challengeResponse = '';

  try{
    challengeResponse = fs.readFileSync(challengesDir + challengeFilename, 'utf8');
  }catch(error){
    res.writeHead(404);
    res.end('Could not find that challenge file.');
    return;
  }

  res.writeHead(200);
  res.end(challengeResponse);
});
